routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Auth::routes();

Route::prefix('auth')->group(function () {
    Route::get('{provider}', 'Auth\AuthController@redirectToProvider')->name('auth.provider');
    Route::get('{provider}/callback', 'Auth\AuthController@handleProviderCallback');
});

Route::prefix('admin')->middleware(['auth', 'role:admin'])->namespace('Admin')->as('admin.')->group(function () {
    Route::get('dashboard', 'ShowDashboard')->name('dashboard');
    Route::resource('posts', 'PostsController');
    Route::delete('/posts/{post}/thumbnail', 'PostsThumbnailController@destroy')->name('posts_thumbnail.destroy');
    Route::resource('users', 'UsersController', ['only' => ['index', 'edit', 'update']]);
    Route::resource('comments', 'CommentsController', ['only' => ['index', 'edit', 'update', 'destroy']]);
});

Route::middleware('auth')->group(function () {
    Route::resource('comments', 'CommentsController', ['only' => ['store', 'destroy']]);
    Route::resource('users', 'UsersController', ['only' => ['edit', 'update']]);
    Route::post('/tokens/{user}', 'TokensController@store')->name('tokens.store');
    Route::delete('/tokens/{user}', 'TokensController@destroy')->name('tokens.destroy');
    Route::resource('newsletter-subscriptions', 'NewsletterSubscriptionsController', ['only' => 'store']);
});

Route::get('/', 'PostsController@index')->name('home');
Route::get('/files/{filename}', 'MediaController@getFile')->name('files');
Route::get('/posts/feed', 'PostsFeedController@index')->name('posts.feed');
Route::resource('posts', 'PostsController', ['only' => 'show']);
Route::resource('users', 'UsersController', ['only' => 'show']);

Route::get('newsletter-subscriptions/unsubscribe', 'NewsletterSubscriptionsController@unsubscribe')->name('newsletter-subscriptions.unsubscribe');

resources/views/admin/shared/sidebar.blade.php
<nav class="col-lg-2 d-none d-lg-block bg-dark sidebar">
  <ul class="nav nav-pills flex-column">
        <li role="presentation" class="nav-item">
            <a class="nav-link {{ Request::is('admin/dashboard') ? 'active' : '' }}" href="{{ route('admin.dashboard') }}">
                <i class="fa fa-tachometer" aria-hidden="true"></i>&nbsp;
                {{ __('dashboard.dashboard') }}
            </a>
        </li>

        <li role="presentation" class="nav-item">
            <a class="nav-link {{ Request::is('admin/posts') || Request::is('admin/posts/*') ? 'active' : '' }}" href="{{ route('admin.posts.index') }}">
                <i class="fa fa-file-text" aria-hidden="true"></i>&nbsp;
                {{ __('dashboard.posts') }}
            </a>
        </li>

        <li role="presentation" class="nav-item">
            <a class="nav-link {{ Request::is('admin/comments') || Request::is('admin/comments/*') ? 'active' : '' }}" href="{{ route('admin.comments.index') }}">
                <i class="fa fa-comments" aria-hidden="true"></i>&nbsp;
                {{ __('dashboard.comments') }}
            </a>
        </li>

        <li role="presentation" class="nav-item">
            <a class="nav-link {{ Request::is('admin/users') || Request::is('admin/users/*') ? 'active' : '' }}" href="{{ route('admin.users.index') }}">
                <i class="fa fa-users" aria-hidden="true"></i>&nbsp;
                {{ __('dashboard.users') }}
            </a>
        </li>
    </ul>
</nav>